import { LevelConfig } from './types';

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    title: 'Bölüm 1: Düz İlerle',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 2, direction: 'RIGHT' },
    target: { x: 4, y: 2 },
    walls: [],
    stars: [{ x: 2, y: 2 }],
    availableBlocks: ['FORWARD'],
    maxBlocks: 5,
  },
  {
    id: 2,
    title: 'Bölüm 2: Viraj Dönüşü',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 1, y: 1, direction: 'RIGHT' },
    target: { x: 3, y: 3 },
    walls: [
      { x: 2, y: 1 },
      { x: 2, y: 2 },
    ],
    stars: [{ x: 3, y: 1 }],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT'],
    maxBlocks: 6,
  },
  {
    id: 3,
    title: 'Bölüm 3: S-Virajı',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 4, direction: 'UP' },
    target: { x: 4, y: 0 },
    walls: [
      { x: 0, y: 2 },
      { x: 1, y: 2 },
      { x: 3, y: 2 },
      { x: 4, y: 2 },
    ],
    stars: [
      { x: 0, y: 3 },
      { x: 2, y: 2 },
      { x: 4, y: 1 },
    ],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT'],
    maxBlocks: 10,
  },
  {
    id: 4,
    title: 'Bölüm 4: Döngüyle Hızlı Geçiş',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 4, direction: 'UP' },
    target: { x: 0, y: 0 },
    walls: [
      { x: 1, y: 1 },
      { x: 1, y: 2 },
      { x: 1, y: 3 },
    ],
    stars: [{ x: 0, y: 2 }],
    availableBlocks: ['FORWARD', 'REPEAT'],
    maxBlocks: 4,
  },
  {
    id: 5,
    title: 'Bölüm 5: Kare Devriyesi',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 1, y: 1, direction: 'RIGHT' },
    target: { x: 1, y: 2 },
    walls: [
      { x: 2, y: 2 },
      { x: 0, y: 0 },
      { x: 4, y: 4 },
    ],
    stars: [
      { x: 3, y: 1 },
      { x: 3, y: 3 },
      { x: 1, y: 3 },
    ],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'REPEAT'],
    maxBlocks: 8,
  },
  {
    id: 6,
    title: 'Bölüm 6: Labirent Ustası',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 0, direction: 'RIGHT' },
    target: { x: 4, y: 4 },
    walls: [
      { x: 1, y: 0 },
      { x: 3, y: 0 },
      { x: 1, y: 2 },
      { x: 2, y: 2 },
      { x: 3, y: 2 },
      { x: 1, y: 4 },
      { x: 3, y: 4 },
    ],
    stars: [
      { x: 0, y: 2 },
      { x: 4, y: 2 },
    ],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'REPEAT'],
    maxBlocks: 12,
  },
];