import { LevelConfig } from './types';

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    title: 'Düz İlerle',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 2, direction: 'RIGHT' },
    target: { x: 4, y: 2 },
    walls: [],
    stars: [{ x: 1, y: 2 }, { x: 2, y: 2 }, { x: 3, y: 2 }],
    availableBlocks: ['FORWARD'],
    maxBlocks: 5,
  },
  {
    id: 2,
    title: 'Köşeyi Dön',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 1, y: 1, direction: 'RIGHT' },
    target: { x: 3, y: 3 },
    walls: [{ x: 2, y: 1 }],
    doors: [{ x: 2, y: 2 }],
    keys: [{ x: 3, y: 1 }],
    stars: [{ x: 2, y: 0 }, { x: 3, y: 2 }, { x: 1, y: 3 }],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT'],
    maxBlocks: 8,
  },
  {
    id: 3,
    title: 'Labirentten Kaçış',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 0, direction: 'RIGHT' },
    target: { x: 4, y: 4 },
    walls: [
      { x: 1, y: 0 }, { x: 3, y: 0 },
      { x: 1, y: 2 }, { x: 2, y: 2 }, { x: 3, y: 2 },
      { x: 1, y: 4 }, { x: 3, y: 4 },
    ],
    stars: [{ x: 2, y: 0 }, { x: 4, y: 2 }, { x: 0, y: 3 }],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT'],
    maxBlocks: 10,
  },
  {
    id: 4,
    title: 'Döngü Gücü: Düz Çizgi',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 4, direction: 'UP' },
    target: { x: 0, y: 0 },
    walls: [{ x: 1, y: 1 }, { x: 1, y: 2 }, { x: 1, y: 3 }],
    stars: [{ x: 0, y: 3 }, { x: 0, y: 2 }, { x: 0, y: 1 }],
    availableBlocks: ['FORWARD', 'REPEAT'],
    maxBlocks: 5,
  },
  {
    id: 5,
    title: 'Zikzak Merdiven',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 4, direction: 'RIGHT' },
    target: { x: 4, y: 0 },
    walls: [{ x: 1, y: 3 }, { x: 3, y: 1 }],
    stars: [{ x: 1, y: 4 }, { x: 2, y: 2 }, { x: 3, y: 0 }],
    availableBlocks: ['FORWARD', 'TURN_LEFT', 'TURN_RIGHT', 'REPEAT'],
    maxBlocks: 10,
  },
  {
    id: 6,
    title: 'Büyük Kare Turu',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 0, direction: 'RIGHT' },
    target: { x: 1, y: 0 },
    walls: [
      { x: 1, y: 1 }, { x: 2, y: 1 }, { x: 3, y: 1 },
      { x: 1, y: 2 }, { x: 2, y: 2 }, { x: 3, y: 2 },
      { x: 1, y: 3 }, { x: 2, y: 3 }, { x: 3, y: 3 },
    ],
    stars: [{ x: 4, y: 0 }, { x: 4, y: 4 }, { x: 0, y: 4 }],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'REPEAT'],
    maxBlocks: 10,
  },
  {
    id: 7,
    title: 'Spiral Girdap',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 0, direction: 'RIGHT' },
    target: { x: 2, y: 2 },
    walls: [
      { x: 1, y: 1 }, { x: 2, y: 1 }, { x: 3, y: 1 },
      { x: 1, y: 2 }, { x: 1, y: 3 },
      { x: 3, y: 2 }, { x: 3, y: 3 },
    ],
    stars: [{ x: 4, y: 0 }, { x: 4, y: 4 }, { x: 0, y: 4 }],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'REPEAT'],
    maxBlocks: 12,
  },
  {
    id: 8,
    title: 'Yıldız Yağmuru',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 2, y: 4, direction: 'UP' },
    target: { x: 2, y: 0 },
    walls: [
      { x: 1, y: 1 }, { x: 3, y: 1 },
      { x: 1, y: 3 }, { x: 3, y: 3 },
    ],
    stars: [{ x: 0, y: 2 }, { x: 2, y: 2 }, { x: 4, y: 2 }],
    availableBlocks: ['FORWARD', 'TURN_LEFT', 'TURN_RIGHT', 'REPEAT'],
    maxBlocks: 12,
  },
  {
    id: 9,
    title: 'İç İçe Zikzak',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 4, direction: 'UP' },
    target: { x: 4, y: 0 },
    walls: [
      { x: 0, y: 1 }, { x: 1, y: 1 }, { x: 2, y: 1 },
      { x: 2, y: 3 }, { x: 3, y: 3 }, { x: 4, y: 3 },
    ],
    stars: [{ x: 1, y: 3 }, { x: 2, y: 2 }, { x: 3, y: 1 }],
    availableBlocks: ['FORWARD', 'TURN_LEFT', 'TURN_RIGHT', 'REPEAT'],
    maxBlocks: 12,
  },
  {
    id: 10,
    title: 'Kod Ustası: Final',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 4, direction: 'UP' },
    target: { x: 4, y: 0 },
    walls: [
      { x: 1, y: 3 }, { x: 1, y: 2 }, { x: 1, y: 1 },
      { x: 3, y: 1 }, { x: 3, y: 2 }, { x: 3, y: 3 },
    ],
    stars: [{ x: 0, y: 0 }, { x: 2, y: 2 }, { x: 4, y: 4 }],
    availableBlocks: ['FORWARD', 'TURN_LEFT', 'TURN_RIGHT', 'REPEAT', 'IF_WALL'],
    maxBlocks: 14,
  },
  {
    id: 11,
    title: 'Çift Kapı Labirenti',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 0, direction: 'RIGHT' },
    target: { x: 4, y: 4 },
    walls: [
      { x: 2, y: 0 }, { x: 2, y: 1 },
      { x: 2, y: 3 }, { x: 2, y: 4 },
    ],
    stars: [{ x: 2, y: 2 }, { x: 0, y: 4 }, { x: 4, y: 0 }],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'REPEAT'],
    maxBlocks: 10,
  },
  {
    id: 12,
    title: 'Engel Algılayıcı (IF Testi)',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 2, direction: 'RIGHT' },
    target: { x: 4, y: 2 },
    walls: [{ x: 2, y: 2 }],
    stars: [{ x: 1, y: 2 }, { x: 2, y: 1 }, { x: 3, y: 2 }],
    availableBlocks: ['FORWARD', 'TURN_LEFT', 'TURN_RIGHT', 'IF_WALL'],
    maxBlocks: 9,
  },
  {
    id: 13,
    title: 'Sonsuzluk Simgesi',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 2, y: 2, direction: 'UP' },
    target: { x: 2, y: 2 },
    walls: [{ x: 1, y: 1 }, { x: 3, y: 3 }],
    stars: [{ x: 2, y: 0 }, { x: 0, y: 2 }, { x: 4, y: 2 }],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'REPEAT'],
    maxBlocks: 12,
  },
  {
    id: 14,
    title: 'Yılan Patikası',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 4, direction: 'RIGHT' },
    target: { x: 4, y: 0 },
    walls: [
      { x: 1, y: 3 }, { x: 2, y: 3 }, { x: 3, y: 3 },
      { x: 1, y: 1 }, { x: 2, y: 1 }, { x: 3, y: 1 },
    ],
    stars: [{ x: 4, y: 4 }, { x: 0, y: 2 }, { x: 4, y: 2 }],
    availableBlocks: ['FORWARD', 'TURN_LEFT', 'TURN_RIGHT', 'REPEAT'],
    maxBlocks: 14,
  },
  {
    id: 15,
    title: 'Köprüden Geçiş',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 2, direction: 'RIGHT' },
    target: { x: 4, y: 2 },
    walls: [
      { x: 1, y: 0 }, { x: 1, y: 1 }, { x: 1, y: 3 }, { x: 1, y: 4 },
      { x: 3, y: 0 }, { x: 3, y: 1 }, { x: 3, y: 3 }, { x: 3, y: 4 },
    ],
    stars: [{ x: 0, y: 1 }, { x: 2, y: 1 }, { x: 2, y: 3 }],
    availableBlocks: ['FORWARD', 'TURN_LEFT', 'TURN_RIGHT', 'REPEAT'],
    maxBlocks: 8,
  },
  {
    id: 16,
    title: 'Piramit Tırmanışı',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 4, direction: 'RIGHT' },
    target: { x: 2, y: 0 },
    walls: [
      { x: 1, y: 4 }, { x: 3, y: 4 },
      { x: 0, y: 2 }, { x: 4, y: 2 },
      { x: 1, y: 1 }, { x: 3, y: 1 },
    ],
    stars: [{ x: 2, y: 4 }, { x: 2, y: 2 }, { x: 2, y: 1 }],
    availableBlocks: ['FORWARD', 'TURN_LEFT', 'TURN_RIGHT', 'REPEAT'],
    maxBlocks: 12,
  },
  {
    id: 17,
    title: 'Çapraz Koridor',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 0, direction: 'RIGHT' },
    target: { x: 4, y: 4 },
    walls: [
      { x: 1, y: 0 }, { x: 2, y: 1 }, { x: 3, y: 2 },
      { x: 0, y: 2 }, { x: 1, y: 3 }, { x: 2, y: 4 },
    ],
    stars: [{ x: 0, y: 4 }, { x: 4, y: 0 }, { x: 2, y: 2 }],
    availableBlocks: ['FORWARD', 'TURN_LEFT', 'TURN_RIGHT', 'REPEAT', 'IF_WALL'],
    maxBlocks: 13,
  },
  {
    id: 18,
    title: 'Ada Turu',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 2, direction: 'UP' },
    target: { x: 4, y: 2 },
    walls: [{ x: 2, y: 1 }, { x: 2, y: 2 }, { x: 2, y: 3 }],
    stars: [{ x: 0, y: 0 }, { x: 2, y: 0 }, { x: 4, y: 0 }],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'REPEAT'],
    maxBlocks: 11,
  },
  {
    id: 19,
    title: 'Labirent Odaları',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 0, direction: 'RIGHT' },
    target: { x: 4, y: 4 },
    walls: [
      { x: 2, y: 0 }, { x: 2, y: 1 }, { x: 2, y: 3 }, { x: 2, y: 4 },
      { x: 0, y: 2 }, { x: 1, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 2 },
    ],
    stars: [{ x: 0, y: 4 }, { x: 4, y: 0 }, { x: 2, y: 2 }],
    availableBlocks: ['FORWARD', 'TURN_LEFT', 'TURN_RIGHT', 'REPEAT'],
    maxBlocks: 12,
  },
  {
    id: 20,
    title: 'Kod Ustası: Şampiyonluk',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 4, direction: 'UP' },
    target: { x: 4, y: 0 },
    walls: [
      { x: 0, y: 2 }, { x: 1, y: 2 },
      { x: 3, y: 2 }, { x: 4, y: 2 },
      { x: 2, y: 0 }, { x: 2, y: 4 },
    ],
    stars: [{ x: 0, y: 0 }, { x: 2, y: 2 }, { x: 4, y: 4 }],
    availableBlocks: ['FORWARD', 'TURN_LEFT', 'TURN_RIGHT', 'REPEAT', 'IF_WALL'],
    maxBlocks: 14,
  },
// --- Anahtar & Kapı Mekaniği (Zorunlu Bariyer Tasarımları 21 - 30) ---
  {
    id: 21,
    title: 'Kilitli Kapı ve Anahtar',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 2, direction: 'RIGHT' },
    target: { x: 4, y: 2 },
    // x=2 sütunu tamamen duvar, tek geçiş (2,2)'deki kapı
    walls: [
      { x: 2, y: 0 }, { x: 2, y: 1 },
      { x: 2, y: 3 }, { x: 2, y: 4 },
    ],
    doors: [{ x: 2, y: 2 }],
    keys: [{ x: 0, y: 0 }],
    stars: [{ x: 1, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 0 }],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'REPEAT'],
    maxBlocks: 10,
  },
  {
    id: 22,
    title: 'Ters Köşe Anahtar',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 4, direction: 'UP' },
    target: { x: 4, y: 0 },
    // Yatay y=2 hattı tamamen duvar, tek geçiş (1,2)'deki kapı
    walls: [
      { x: 0, y: 2 }, { x: 2, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 2 },
    ],
    doors: [{ x: 1, y: 2 }],
    keys: [{ x: 4, y: 4 }],
    stars: [{ x: 0, y: 0 }, { x: 2, y: 3 }, { x: 3, y: 1 }],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'REPEAT'],
    maxBlocks: 12,
  },
  {
    id: 23,
    title: 'Çift Kilitli Geçit',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 2, direction: 'RIGHT' },
    target: { x: 4, y: 2 },
    // x=1 ve x=3 sütunları komple duvar; her ikisinin de ortasında zorunlu kapı var
    walls: [
      { x: 1, y: 0 }, { x: 1, y: 1 }, { x: 1, y: 3 }, { x: 1, y: 4 },
      { x: 3, y: 0 }, { x: 3, y: 1 }, { x: 3, y: 3 }, { x: 3, y: 4 },
    ],
    doors: [{ x: 1, y: 2 }, { x: 3, y: 2 }],
    keys: [{ x: 0, y: 0 }, { x: 2, y: 0 }],
    stars: [{ x: 0, y: 4 }, { x: 2, y: 2 }, { x: 4, y: 4 }],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'REPEAT'],
    maxBlocks: 14,
  },
  {
    id: 24,
    title: 'Hazine Odası',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 4, direction: 'UP' },
    target: { x: 2, y: 2 },
    // (2,2) hücresi duvarlarla çevrili, tek girişi (2,3)'teki kapı
    walls: [
      { x: 1, y: 1 }, { x: 2, y: 1 }, { x: 3, y: 1 },
      { x: 1, y: 2 },               { x: 3, y: 2 },
      { x: 1, y: 3 },               { x: 3, y: 3 },
    ],
    doors: [{ x: 2, y: 3 }],
    keys: [{ x: 4, y: 0 }],
    stars: [{ x: 0, y: 0 }, { x: 4, y: 4 }, { x: 2, y: 0 }],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'REPEAT'],
    maxBlocks: 12,
  },
  {
    id: 25,
    title: 'Kilitli Labirent',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 0, direction: 'RIGHT' },
    target: { x: 4, y: 4 },
    // Labirenti ikiye bölen x=2 duvarı; tek geçiş noktası (2,3)'teki kapı
    walls: [
      { x: 2, y: 0 }, { x: 2, y: 1 }, { x: 2, y: 2 }, { x: 2, y: 4 },
      { x: 0, y: 2 }, { x: 4, y: 2 },
    ],
    doors: [{ x: 2, y: 3 }],
    keys: [{ x: 0, y: 4 }],
    stars: [{ x: 1, y: 1 }, { x: 3, y: 3 }, { x: 4, y: 0 }],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'REPEAT'],
    maxBlocks: 12,
  },
  {
    id: 26,
    title: 'Köşe Zindanı',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 0, direction: 'DOWN' },
    target: { x: 4, y: 4 },
    // Hedef köşe (4,4) duvarlarla kapatılmış, girişi (3,4) kapısı
    walls: [
      { x: 3, y: 3 }, { x: 4, y: 3 },
      { x: 1, y: 1 }, { x: 2, y: 1 }, { x: 1, y: 3 },
    ],
    doors: [{ x: 3, y: 4 }],
    keys: [{ x: 4, y: 0 }],
    stars: [{ x: 0, y: 4 }, { x: 2, y: 2 }, { x: 2, y: 4 }],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'REPEAT'],
    maxBlocks: 13,
  },
  {
    id: 27,
    title: 'Geçit Nöbetçisi',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 2, direction: 'RIGHT' },
    target: { x: 4, y: 2 },
    // x=2 duvarı tüm ızgarayı dikey keser, tek geçiş (2,2)'deki kapıdır
    walls: [
      { x: 2, y: 0 }, { x: 2, y: 1 },
      { x: 2, y: 3 }, { x: 2, y: 4 },
    ],
    doors: [{ x: 2, y: 2 }],
    keys: [{ x: 0, y: 4 }],
    stars: [{ x: 1, y: 0 }, { x: 3, y: 0 }, { x: 3, y: 4 }],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'IF_WALL', 'REPEAT'],
    maxBlocks: 11,
  },
  {
    id: 28,
    title: 'Korumalı Kale',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 4, direction: 'RIGHT' },
    target: { x: 2, y: 0 },
    // Üst taraf y=1 seviyesinde duvarla kapatılmış, tek giriş (2,1)'deki kapı
    walls: [
      { x: 0, y: 1 }, { x: 1, y: 1 }, { x: 3, y: 1 }, { x: 4, y: 1 },
      { x: 2, y: 3 },
    ],
    doors: [{ x: 2, y: 1 }],
    keys: [{ x: 4, y: 4 }],
    stars: [{ x: 0, y: 2 }, { x: 4, y: 2 }, { x: 2, y: 2 }],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'REPEAT'],
    maxBlocks: 12,
  },
  {
    id: 29,
    title: 'İkiz Barikat',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 2, y: 4, direction: 'UP' },
    target: { x: 2, y: 0 },
    // y=3 ve y=1 hatları komple duvar; her ikisinin de tek geçişi kapıdır
    walls: [
      { x: 0, y: 3 }, { x: 1, y: 3 }, { x: 3, y: 3 }, { x: 4, y: 3 },
      { x: 0, y: 1 }, { x: 1, y: 1 }, { x: 3, y: 1 }, { x: 4, y: 1 },
    ],
    doors: [{ x: 2, y: 3 }, { x: 2, y: 1 }],
    keys: [{ x: 0, y: 4 }, { x: 4, y: 2 }],
    stars: [{ x: 4, y: 4 }, { x: 0, y: 2 }, { x: 2, y: 2 }],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'REPEAT'],
    maxBlocks: 15,
  },
  {
    id: 30,
    title: 'Şato Meydan Okuması: Usta',
    gridSize: { rows: 5, cols: 5 },
    start: { x: 0, y: 4, direction: 'UP' },
    target: { x: 4, y: 0 },
    // Hedef bayrak etrafı tamamen duvarlı (sağ üst köşe), girişi (3,0)'daki kapı
    walls: [
      { x: 3, y: 1 }, { x: 4, y: 1 },
      { x: 1, y: 1 }, { x: 1, y: 2 }, { x: 1, y: 3 },
      { x: 2, y: 3 },
    ],
    doors: [{ x: 3, y: 0 }],
    keys: [{ x: 4, y: 4 }],
    stars: [{ x: 0, y: 0 }, { x: 2, y: 2 }, { x: 2, y: 4 }],
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'REPEAT', 'IF_WALL'],
    maxBlocks: 16,
  },
];